### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by WangYx-Ethan** [chenyuntc/pytorch-best-practice#2]
python main.py train --data-root=./data/train --use-gpu=True --env=classifier

Traceback (most recent call last):
  File "main.py", line 170, in <module>
    import fire
  File "C:\Users\---\Anaconda2\envs\py36\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\---\Anaconda2\envs\py36\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\---\Anaconda2\envs\py36\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 48, in train
    def train(**kwargs):
NameError: name 'opt' is not defined

**Comment by suzhengpeng** [comment]
我也遇到了同样的问题。。请问你解决了吗？

**Comment by P-DX** [comment]
main.py中
import ...opt 
这句之前加随意一句注释
